// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoko.Server.Data;

#nullable disable

namespace Shoko.Server.Data.Migrations
{
    [DbContext(typeof(ShokoDbContext))]
    [Migration("20260509114039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime", b =>
                {
                    b.Property<int>("AniDB_AnimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ANNID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AllCinemaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllTitles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnisonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvgReviewRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BangumiID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeginYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrunchyrollID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeDescUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeCountNormal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeCountSpecial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FunimationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("HiDiveID")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LainID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LatestEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picname")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Restricted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Site_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Site_JP")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SyoboiID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempVoteCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VNDBID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WikipediaJP_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wikipedia_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("AniDB_AnimeID");

                    b.ToTable("AniDB_Anime", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_AnimeUpdate", b =>
                {
                    b.Property<int>("AniDB_AnimeUpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AniDB_AnimeUpdateID");

                    b.ToTable("AniDB_AnimeUpdate", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_Character", b =>
                {
                    b.Property<int>("AniDB_Anime_CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AppearanceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_Anime_CharacterID");

                    b.ToTable("AniDB_Anime_Character", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_Character_Creator", b =>
                {
                    b.Property<int>("AniDB_Anime_Character_CreatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_Anime_Character_CreatorID");

                    b.ToTable("AniDB_Anime_Character_Creator", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_PreferredImage", b =>
                {
                    b.Property<int>("AniDB_Anime_PreferredImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ImageSource")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ImageType")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_Anime_PreferredImageID");

                    b.ToTable("AniDB_Anime_PreferredImage", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_Relation", b =>
                {
                    b.Property<int>("AniDB_Anime_RelationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AniDB_Anime_RelationID");

                    b.ToTable("AniDB_Anime_Relation", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_Similar", b =>
                {
                    b.Property<int>("AniDB_Anime_SimilarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Approval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimilarAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_Anime_SimilarID");

                    b.ToTable("AniDB_Anime_Similar", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_Staff", b =>
                {
                    b.Property<int>("AniDB_Anime_StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_Anime_StaffID");

                    b.ToTable("AniDB_Anime_Staff", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_Tag", b =>
                {
                    b.Property<int>("AniDB_Anime_TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocalSpoiler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_Anime_TagID");

                    b.ToTable("AniDB_Anime_Tag", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Anime_Title", b =>
                {
                    b.Property<int>("AniDB_Anime_TitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AniDB_Anime_TitleID");

                    b.ToTable("AniDB_Anime_Title", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Character", b =>
                {
                    b.Property<int>("AniDB_CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_CharacterID");

                    b.ToTable("AniDB_Character", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Creator", b =>
                {
                    b.Property<int>("AniDB_CreatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishHomepageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishWikiUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JapaneseHomepageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("JapaneseWikiUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_CreatorID");

                    b.ToTable("AniDB_Creator", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Episode", b =>
                {
                    b.Property<int>("AniDB_EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("EpisodeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LengthSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Votes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AniDB_EpisodeID");

                    b.ToTable("AniDB_Episode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Episode_PreferredImage", b =>
                {
                    b.Property<int>("AniDB_Episode_PreferredImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ImageSource")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ImageType")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_Episode_PreferredImageID");

                    b.ToTable("AniDB_Episode_PreferredImage", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Episode_Title", b =>
                {
                    b.Property<int>("AniDB_Episode_TitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniDB_EpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AniDB_Episode_TitleID");

                    b.ToTable("AniDB_Episode_Title", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_GroupStatus", b =>
                {
                    b.Property<int>("AniDB_GroupStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LastEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_GroupStatusID");

                    b.ToTable("AniDB_GroupStatus", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Message", b =>
                {
                    b.Property<int>("AniDB_MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromUserId")
                        .HasColumnName("FromUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_MessageID");

                    b.ToTable("AniDB_Message", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_NotifyQueue", b =>
                {
                    b.Property<int>("AniDB_NotifyQueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_NotifyQueueID");

                    b.ToTable("AniDB_NotifyQueue", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.AniDB.AniDB_Tag", b =>
                {
                    b.Property<int>("AniDB_TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GlobalSpoiler")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTagID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagNameOverride")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagNameSource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TagName");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.HasKey("AniDB_TagID");

                    b.ToTable("AniDB_Tag", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.CrossReference.CrossRef_AniDB_MAL", b =>
                {
                    b.Property<int>("CrossRef_AniDB_MALID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MALID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrossRef_AniDB_MALID");

                    b.ToTable("CrossRef_AniDB_MAL");
                });

            modelBuilder.Entity("Shoko.Server.Models.CrossReference.CrossRef_AniDB_TMDB_Episode", b =>
                {
                    b.Property<int>("CrossRef_AniDB_TMDB_EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MatchRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrossRef_AniDB_TMDB_EpisodeID");

                    b.ToTable("CrossRef_AniDB_TMDB_Episode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.CrossReference.CrossRef_AniDB_TMDB_Movie", b =>
                {
                    b.Property<int>("CrossRef_AniDB_TMDB_MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MatchRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrossRef_AniDB_TMDB_MovieID");

                    b.ToTable("CrossRef_AniDB_TMDB_Movie", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.CrossReference.CrossRef_AniDB_TMDB_Show", b =>
                {
                    b.Property<int>("CrossRef_AniDB_TMDB_ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnidbAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MatchRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrossRef_AniDB_TMDB_ShowID");

                    b.ToTable("CrossRef_AniDB_TMDB_Show", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.CrossReference.CrossRef_CustomTag", b =>
                {
                    b.Property<int>("CrossRef_CustomTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrossRefID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrossRefType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomTagID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrossRef_CustomTagID");

                    b.ToTable("CrossRef_CustomTag");
                });

            modelBuilder.Entity("Shoko.Server.Models.CrossReference.CrossRef_File_Episode", b =>
                {
                    b.Property<int>("CrossRef_File_EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Percentage")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrossRef_File_EpisodeID");

                    b.ToTable("CrossRef_File_Episode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Internal.AuthTokens", b =>
                {
                    b.Property<int>("AuthID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthID");

                    b.ToTable("AuthTokens", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Internal.ScheduledUpdate", b =>
                {
                    b.Property<int>("ScheduledUpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduledUpdateID");

                    b.ToTable("ScheduledUpdate");
                });

            modelBuilder.Entity("Shoko.Server.Models.Internal.Versions", b =>
                {
                    b.Property<int>("VersionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionProgram")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionRevision")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VersionsID");

                    b.ToTable("Versions", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Legacy.Playlist", b =>
                {
                    b.Property<int>("PlaylistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPlayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayUnwatched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayWatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaylistItems")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaylistName")
                        .HasColumnType("TEXT");

                    b.HasKey("PlaylistID");

                    b.ToTable("Playlist", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Legacy.Scan", b =>
                {
                    b.Property<int>("ScanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTIme")
                        .HasColumnName("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportFolders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScanID");

                    b.ToTable("Scan", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Legacy.ScanFile", b =>
                {
                    b.Property<int>("ScanFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashResult")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportFolderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoLocal_Place_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScanFileID");

                    b.ToTable("ScanFile", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Release.StoredReleaseInfo", b =>
                {
                    b.Property<int>("StoredReleaseInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ED2K")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddedAudioLanguages")
                        .HasColumnType("TEXT")
                        .HasColumnName("AudioLanguages");

                    b.Property<string>("EmbeddedCrossReferences")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CrossReferences");

                    b.Property<string>("EmbeddedHashes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Hashes");

                    b.Property<string>("EmbeddedSubtitleLanguages")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubtitleLanguages");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupID")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCensored")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsChaptered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrupted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCreditless")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProvidedFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseURI")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleasedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoredReleaseInfoID");

                    b.ToTable("StoredReleaseInfo", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Release.StoredReleaseInfo_MatchAttempt", b =>
                {
                    b.Property<int>("StoredReleaseInfo_MatchAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptEndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttemptStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ED2K")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddedAttemptProviderNames")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AttemptProviderNames");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProviderID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasColumnType("TEXT");

                    b.HasKey("StoredReleaseInfo_MatchAttemptID");

                    b.ToTable("StoredReleaseInfo_MatchAttempt", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.AnimeEpisode", b =>
                {
                    b.Property<int>("AnimeEpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniDB_EpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeSeriesID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeNameOverride")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeEpisodeID");

                    b.ToTable("AnimeEpisode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.AnimeEpisode_User", b =>
                {
                    b.Property<int>("AnimeEpisode_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbsoluteUserRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeSeriesID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JMMUserID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoppedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AnimeEpisode_UserID");

                    b.ToTable("AnimeEpisode_User", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.AnimeGroup", b =>
                {
                    b.Property<int>("AnimeGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimeGroupParentID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultAnimeSeriesID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EpisodeAddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsManuallyNamed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LatestEpisodeAirDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MainAniDBAnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingEpisodeCountGroups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverrideDescription")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeGroupID");

                    b.ToTable("AnimeGroup", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.AnimeGroup_User", b =>
                {
                    b.Property<int>("AnimeGroup_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeGroupID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JMMUserID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoppedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnwatchedEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchedEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeGroup_UserID");

                    b.ToTable("AnimeGroup_User", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.AnimeSeries", b =>
                {
                    b.Property<int>("AnimeSeriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AirsOn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniDB_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeGroupID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultAudioLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSubtitleLanguage")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisableAutoMatchFlags")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EpisodeAddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HiddenMissingEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenMissingEpisodeCountGroups")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LatestEpisodeAirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LatestLocalEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingEpisodeCountGroups")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesNameOverride")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AnimeSeriesID");

                    b.ToTable("AnimeSeries", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.AnimeSeries_User", b =>
                {
                    b.Property<int>("AnimeSeries_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbsoluteUserRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeSeriesID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenUnwatchedEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JMMUserID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEpisodeUpdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVideoUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoppedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnwatchedEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserRatingVoteType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchedEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeSeries_UserID");

                    b.ToTable("AnimeSeries_User", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.CustomTag", b =>
                {
                    b.Property<int>("CustomTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomTagID");

                    b.ToTable("CustomTag");
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.FileNameHash", b =>
                {
                    b.Property<int>("FileNameHashID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FileNameHashID");

                    b.ToTable("FileNameHash", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.FilterPreset", b =>
                {
                    b.Property<int>("FilterPresetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApplyAtSeriesLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Expression")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilterType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFilterPresetID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortingExpression")
                        .HasColumnType("TEXT");

                    b.HasKey("FilterPresetID");

                    b.ToTable("FilterPreset", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.JMMUser", b =>
                {
                    b.Property<int>("JMMUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AvatarImageBlob")
                        .HasColumnType("BLOB");

                    b.Property<int?>("CanEditServerSettings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HideCategories")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsAniDBUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsTraktUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlexToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlexUsers")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAvatarImageMetadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("AvatarImageMetadata");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JMMUserID");

                    b.ToTable("JMMUser", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.ShokoManagedFolder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ImportFolderID");

                    b.Property<bool>("IsDropDestination")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDropSource")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImportFolderName");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImportFolderLocation");

                    b.HasKey("ID");

                    b.ToTable("ImportFolder", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.StoredRelocationPipe", b =>
                {
                    b.Property<int>("StoredRelocationPipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Configuration")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderID")
                        .HasColumnType("TEXT");

                    b.HasKey("StoredRelocationPipeID");

                    b.ToTable("StoredRelocationPipe", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.VideoLocal", b =>
                {
                    b.Property<int>("VideoLocalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTimeImported")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HashSource")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVariation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAVDumpVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAVDumped")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MediaInfo")
                        .HasColumnType("BLOB")
                        .HasColumnName("MediaBlob");

                    b.Property<int>("MediaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MyListID")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoLocalID");

                    b.ToTable("VideoLocal", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.VideoLocal_HashDigest", b =>
                {
                    b.Property<int>("VideoLocal_HashDigestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoLocalID")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoLocal_HashDigestID");

                    b.ToTable("VideoLocal_HashDigest", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.VideoLocal_Place", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("VideoLocal_Place_ID");

                    b.Property<int>("ManagedFolderID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ImportFolderID");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FilePath");

                    b.Property<int>("VideoID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VideoLocalID");

                    b.HasKey("ID");

                    b.ToTable("VideoLocal_Place", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.Shoko.VideoLocal_User", b =>
                {
                    b.Property<int>("VideoLocal_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JMMUserID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResumePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoLocalID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoLocal_UserID");

                    b.ToTable("VideoLocal_User", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering", b =>
                {
                    b.Property<int>("TMDB_AlternateOrderingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbEpisodeGroupCollectionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbNetworkID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_AlternateOrderingID");

                    b.ToTable("TMDB_AlternateOrdering", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Episode", b =>
                {
                    b.Property<int>("TMDB_AlternateOrdering_EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbEpisodeGroupCollectionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbEpisodeGroupID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_AlternateOrdering_EpisodeID");

                    b.ToTable("TMDB_AlternateOrdering_Episode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Season", b =>
                {
                    b.Property<int>("TMDB_AlternateOrdering_SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbEpisodeGroupCollectionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbEpisodeGroupID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_AlternateOrdering_SeasonID");

                    b.ToTable("TMDB_AlternateOrdering_Season", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Collection", b =>
                {
                    b.Property<int>("TMDB_CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbCollectionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_CollectionID");

                    b.ToTable("TMDB_Collection", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Collection_Movie", b =>
                {
                    b.Property<int>("TMDB_Collection_MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbCollectionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Collection_MovieID");

                    b.ToTable("TMDB_Collection_Movie", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company", b =>
                {
                    b.Property<int>("TMDB_CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbCompanyID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_CompanyID");

                    b.ToTable("TMDB_Company", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company_Entity", b =>
                {
                    b.Property<int>("TMDB_Company_EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleasedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbCompanyID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TmdbEntityType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Company_EntityID");

                    b.ToTable("TMDB_Company_Entity", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode", b =>
                {
                    b.Property<int>("TMDB_EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Runtime");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvdbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_EpisodeID");

                    b.ToTable("TMDB_Episode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode_Cast", b =>
                {
                    b.Property<int>("TMDB_Episode_CastID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGuestRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Episode_CastID");

                    b.ToTable("TMDB_Episode_Cast", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode_Crew", b =>
                {
                    b.Property<int>("TMDB_Episode_CrewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Episode_CrewID");

                    b.ToTable("TMDB_Episode_Crew", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image", b =>
                {
                    b.Property<int>("TMDB_ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_ImageID");

                    b.ToTable("TMDB_Image", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Entity", b =>
                {
                    b.Property<int>("TMDB_Image_EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleasedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TmdbEntityType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Image_EntityID");

                    b.ToTable("TMDB_Image_Entity", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie", b =>
                {
                    b.Property<int>("TMDB_MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRatings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbMovieID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionCountries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleasedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Runtime");

                    b.Property<int?>("TmdbCollectionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_MovieID");

                    b.ToTable("TMDB_Movie", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie_Cast", b =>
                {
                    b.Property<int>("TMDB_Movie_CastID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Movie_CastID");

                    b.ToTable("TMDB_Movie_Cast", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie_Crew", b =>
                {
                    b.Property<int>("TMDB_Movie_CrewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Movie_CrewID");

                    b.ToTable("TMDB_Movie_Crew", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Network", b =>
                {
                    b.Property<int>("TMDB_NetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOrphanedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbNetworkID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_NetworkID");

                    b.ToTable("TMDB_Network", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview", b =>
                {
                    b.Property<int>("TMDB_OverviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TMDB_OverviewID");

                    b.ToTable("TMDB_Overview", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Person", b =>
                {
                    b.Property<int>("TMDB_PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeathDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishBiography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOrphanedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_PersonID");

                    b.ToTable("TMDB_Person", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Season", b =>
                {
                    b.Property<int>("TMDB_SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_SeasonID");

                    b.ToTable("TMDB_Season", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Show", b =>
                {
                    b.Property<int>("TMDB_ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlternateOrderingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRatings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstAiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastAiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredAlternateOrderingID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionCountries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvdbShowID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_ShowID");

                    b.ToTable("TMDB_Show", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Show_Network", b =>
                {
                    b.Property<int>("TMDB_Show_NetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbNetworkID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Show_NetworkID");

                    b.ToTable("TMDB_Show_Network", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title", b =>
                {
                    b.Property<int>("TMDB_TitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TMDB_TitleID");

                    b.ToTable("TMDB_Title", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
